### ISSUE TITLE
Move to 30 seconds repository

### ISSUE THREAD

**Issue by NothingEverHappens** [nycJSorg/30-seconds-of-angular#225]

**Comment by fejes713** [comment]
Fantastic ❤️Can't wait to merge this! 

We would like every team member to remain full access to the repo so I just need the following:

- List of usernames who closely worked on this (main contributors of the project). 
- A single person who will be in charge of the project (will be added to the core team of 30-seconds)m my vote goes for @kirjs since he started this and I know him personally 😄 

We will merge this project as soon as you give me the list of usernames, and we will make a separate Angular team on Github where you will have all rights to the projects.

During the following weeks, we will work a bit on the design side and do a few launches 👍 

Thanks for the amazing work!

**Comment by fetis** [comment]
Hi @fejes713, on behalf @kirjs here's the list (I approved it with Kirill)

@kirjs (project lead)
@thekiba
@fetis
@alex-bu-93
@irustm
@alQlagin

**Comment by fejes713** [comment]
Hey, @fetis I just invited all of the mentioned members to `30-seconds/angular` team. We're one step closer to merging 👍

**Comment by Chalarangelo** [comment]
Right about time! First of all, I would like to thank you all for the great work you have done so far. Also, I would like to welcome all of the new members joining our organization. 

You can move the repository to our organization as soon as you are ready. You can contact me or @fejes713 about the transfer, shall you need any help. As soon as the repo is migrated to our org, I will give the Angular team write permissions to it and we'll be set to go. 

Looking forward to working with you guys!

**Comment by kirjs** [comment]
Hey @Chalarangelo and @fejes713 thanks for the warm welcome! 

We're excited to get a new home for the repo 🔥 

Just a heads up, we're going to be in a slow mode for the next few weeks as some of us are on vacation, but will be back after with more cool stuff.

**Comment by Chalarangelo** [comment]
@kirjs Not a problem, same here. 😉
